// src/components/ui/frame/frame.svelte
<script lang="ts">
  import type { FrameProps } from "./frame.types";
  import type { HTMLAttributes } from "svelte/elements";
  import { setupSvgRenderer } from "@/helpers/frame";
  import { cn } from "@/helpers/classname";
  import { onMount } from "svelte";

  let {
    paths,
    enableBackdropBlur = false,
    enableViewBox = false,
    class: className = "",
    ...rest
  }: FrameProps & HTMLAttributes<SVGSVGElement> = $props();
  let svgEl = $state<SVGSVGElement | null>(null);

  onMount(() => {
    if (svgEl?.parentElement) {
      const instance = setupSvgRenderer({
        el: svgEl,
        paths,
        enableBackdropBlur,
        enableViewBox,
      });
      return () => instance.destroy();
    }
  });
</script>

<svg
  {...rest}
  bind:this={svgEl}
  class={cn("absolute inset-0 size-full", className)}
/>

// src/components/ui/frame/frame.tsx
import { cn } from "@/helpers/classname";
import { setupSvgRenderer, type Paths } from "@/helpers/frame";
import type { ComponentProps } from "preact";
import { memo } from "preact/compat";
import { useEffect, useRef } from "preact/hooks";
import type { FrameProps } from "./frame.types";

const Frame = ({
  className,
  paths,
  enableBackdropBlur,
  enableViewBox,
  ...props
}: FrameProps & ComponentProps<"svg">) => {
  const svgRef = useRef<SVGSVGElement | null>(null);

  useEffect(() => {
    if (svgRef.current && svgRef.current.parentElement) {
      const instance = setupSvgRenderer({
        el: svgRef.current,
        paths,
        enableBackdropBlur,
        enableViewBox,
      });

      return () => instance.destroy();
    }
  }, [paths]);

  return (
    <svg
      {...props}
      className={cn(["absolute inset-0 size-full", className])}
      xmlns="http://www.w3.org/2000/svg"
      ref={svgRef}
    />
  );
};

export default memo(Frame);
